# Generated by Django 4.1.5 on 2023-02-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mascoteros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
