# Generated by Django 4.1.5 on 2023-02-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mascoteros', '0002_alter_animal_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='imagen',
            field=models.ImageField(upload_to='images_animales'),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='imagen',
            field=models.ImageField(upload_to='images_establecimientos'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(upload_to='images_productos'),
        ),
    ]
